repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.14
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
        args: [--check]

  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: .venv/Scripts/pyright.exe
        language: system
        types: [python]
        pass_filenames: false
        args: [backend/]
